### ISSUE TITLE
Possibilité de rechercher par code INSEE ou par un autre champ

### ISSUE THREAD

**Issue by MathRobin** [sgmap/codes-postaux#14]
La recherche par code postal même si très utile est vite limitée. Est-ce que vous envisagez qu'on puisse rechercher aussi par code insee ou par nom de ville ?

**Comment by jdesboeufs** [comment]
Bonjour,
Pour le moment ces fonctionnalités sont dans la GéoAPI : https://api.gouv.fr/api/geoapi.html
Néanmoins je pense aussi qu'on pourrait en extraire une bibliothèque autonome.

**Comment by MattiSG** [comment]
Ce package s'appelle `code-postaux` 😉 Pour le reste, voir le commentaire de @jdesboeufs 🙂

**Comment by MathRobin** [comment]
Pas de soucis, l'argument se tient aussi. Pour ceux que ça intéresse, j'ai créé il y a quelques mois un package npm similaire : https://github.com/MathRobin/codepostaux
Il fait recherche par code postaux et par code insee.
